// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Repositories;

#nullable disable

namespace LudusAppoint.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    partial class RepositoryContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CustomerAppointmentOfferedServices", b =>
                {
                    b.Property<int>("CustomerAppointmentId")
                        .HasColumnType("int");

                    b.Property<int>("OfferedServicesId")
                        .HasColumnType("int");

                    b.HasKey("CustomerAppointmentId", "OfferedServicesId");

                    b.HasIndex("OfferedServicesId");

                    b.ToTable("CustomerAppointmentOfferedServices");

                    b.HasData(
                        new
                        {
                            CustomerAppointmentId = 1,
                            OfferedServicesId = 1
                        },
                        new
                        {
                            CustomerAppointmentId = 1,
                            OfferedServicesId = 3
                        },
                        new
                        {
                            CustomerAppointmentId = 2,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            CustomerAppointmentId = 2,
                            OfferedServicesId = 1
                        },
                        new
                        {
                            CustomerAppointmentId = 2,
                            OfferedServicesId = 3
                        },
                        new
                        {
                            CustomerAppointmentId = 3,
                            OfferedServicesId = 1
                        },
                        new
                        {
                            CustomerAppointmentId = 4,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            CustomerAppointmentId = 4,
                            OfferedServicesId = 1
                        },
                        new
                        {
                            CustomerAppointmentId = 5,
                            OfferedServicesId = 1
                        },
                        new
                        {
                            CustomerAppointmentId = 5,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            CustomerAppointmentId = 6,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            CustomerAppointmentId = 6,
                            OfferedServicesId = 3
                        },
                        new
                        {
                            CustomerAppointmentId = 7,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            CustomerAppointmentId = 8,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            CustomerAppointmentId = 8,
                            OfferedServicesId = 4
                        },
                        new
                        {
                            CustomerAppointmentId = 8,
                            OfferedServicesId = 1
                        },
                        new
                        {
                            CustomerAppointmentId = 9,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            CustomerAppointmentId = 10,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            CustomerAppointmentId = 10,
                            OfferedServicesId = 1
                        },
                        new
                        {
                            CustomerAppointmentId = 10,
                            OfferedServicesId = 3
                        });
                });

            modelBuilder.Entity("EmployeeOfferedServices", b =>
                {
                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("OfferedServicesId")
                        .HasColumnType("int");

                    b.HasKey("EmployeeId", "OfferedServicesId");

                    b.HasIndex("OfferedServicesId");

                    b.ToTable("EmployeeOfferedServices");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 1
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 3
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 4
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 5
                        },
                        new
                        {
                            EmployeeId = 2,
                            OfferedServicesId = 2
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 6
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 7
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 8
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 9
                        },
                        new
                        {
                            EmployeeId = 1,
                            OfferedServicesId = 10
                        });
                });

            modelBuilder.Entity("Entities.Models.AgeGroup", b =>
                {
                    b.Property<int>("AgeGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AgeGroupId"));

                    b.Property<int>("MaxAge")
                        .HasColumnType("int");

                    b.Property<int>("MinAge")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AgeGroupId");

                    b.HasIndex("TenantId");

                    b.HasIndex("MinAge", "MaxAge")
                        .IsUnique();

                    b.ToTable("AgeGroups");

                    b.HasData(
                        new
                        {
                            AgeGroupId = 1,
                            MaxAge = 17,
                            MinAge = 0,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            AgeGroupId = 2,
                            MaxAge = 75,
                            MinAge = 18,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            AgeGroupId = 3,
                            MaxAge = 125,
                            MinAge = 76,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Entities.Models.ApplicationSetting", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.HasIndex("TenantId");

                    b.ToTable("ApplicationSetting");

                    b.HasData(
                        new
                        {
                            Key = "SupportedGenders",
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Value = "Male,Female"
                        },
                        new
                        {
                            Key = "CompanyName",
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Value = "Hair Center"
                        },
                        new
                        {
                            Key = "CompanyLogoURL",
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Value = "\\assets\\img\\logo.jpg"
                        },
                        new
                        {
                            Key = "Currency",
                            LastModified = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111"),
                            Value = "tr-TR"
                        });
                });

            modelBuilder.Entity("Entities.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasFilter("[PhoneNumber] IS NOT NULL");

                    b.HasIndex("TenantId");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Entities.Models.BookingFlowConfig", b =>
                {
                    b.Property<int>("BookingFlowConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BookingFlowConfigId"));

                    b.Property<string>("AllStepsInOrder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[\"Services\", \"DateTime\", \"RoomSelection\", \"Employee\"]");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");

                    b.Property<string>("EnabledStepsInOrder")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("[\"Services\", \"DateTime\", \"RoomSelection\", \"Employee\"]");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("BookingFlowConfigId");

                    b.HasIndex("BranchId");

                    b.HasIndex("TenantId", "BranchId")
                        .IsUnique();

                    b.ToTable("BookingFlowConfigs");
                });

            modelBuilder.Entity("Entities.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchId"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchPhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("District")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Neighbourhood")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ReservationInAdvanceDayLimit")
                        .HasColumnType("int");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("BranchId");

                    b.HasIndex("TenantId");

                    b.ToTable("Branches");

                    b.HasData(
                        new
                        {
                            BranchId = 1,
                            Address = "no 13 a",
                            BranchEmail = "businessmail@business.com",
                            BranchName = "Hacıhalil Şube",
                            BranchPhoneNumber = "+90 537 025 52 80",
                            City = "Kocaeli",
                            Country = "Turkey",
                            District = "Gebze",
                            Neighbourhood = "Hacıhalil",
                            ReservationInAdvanceDayLimit = 60,
                            Status = true,
                            Street = "Kızılay caddesi, 1203. Sk.",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            BranchId = 2,
                            Address = "No:68",
                            BranchEmail = "businessmail@business.com",
                            BranchName = "Gebze Şube",
                            BranchPhoneNumber = "+90 537 025 52 80",
                            City = "Kocaeli",
                            Country = "Turkey",
                            District = "Gebze",
                            Neighbourhood = "Osman Yılmaz",
                            ReservationInAdvanceDayLimit = 60,
                            Status = false,
                            Street = "Kızılay Cd.",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Entities.Models.CustomerAppointment", b =>
                {
                    b.Property<int>("CustomerAppointmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerAppointmentId"));

                    b.Property<int>("AgeGroupId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ApproximateDuration")
                        .HasColumnType("time");

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EMail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CustomerAppointmentId");

                    b.HasIndex("AgeGroupId");

                    b.HasIndex("BranchId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId");

                    b.ToTable("CustomerAppointments");

                    b.HasData(
                        new
                        {
                            CustomerAppointmentId = 1,
                            AgeGroupId = 1,
                            ApproximateDuration = new TimeSpan(0, 0, 30, 0, 0),
                            BranchId = 1,
                            EMail = "alice.smith@example.com",
                            EmployeeId = 1,
                            Gender = 1,
                            Name = "Alice",
                            PhoneNumber = "+90 123 456 7891",
                            Price = 150m,
                            StartDateTime = new DateTime(2026, 1, 18, 10, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            Surname = "Smith",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 2,
                            AgeGroupId = 2,
                            ApproximateDuration = new TimeSpan(0, 0, 45, 0, 0),
                            BranchId = 1,
                            EMail = "bob.johnson@example.com",
                            EmployeeId = 2,
                            Gender = 0,
                            Name = "Bob",
                            PhoneNumber = "+90 123 456 7892",
                            Price = 200m,
                            StartDateTime = new DateTime(2026, 1, 18, 11, 30, 0, 0, DateTimeKind.Local),
                            Status = 0,
                            Surname = "Johnson",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 3,
                            AgeGroupId = 3,
                            ApproximateDuration = new TimeSpan(0, 1, 0, 0, 0),
                            BranchId = 1,
                            EMail = "charlie.brown@example.com",
                            EmployeeId = 1,
                            Gender = 0,
                            Name = "Charlie",
                            PhoneNumber = "+90 123 456 7893",
                            Price = 250m,
                            StartDateTime = new DateTime(2026, 1, 18, 14, 0, 0, 0, DateTimeKind.Local),
                            Status = 3,
                            Surname = "Brown",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 4,
                            AgeGroupId = 2,
                            ApproximateDuration = new TimeSpan(0, 0, 40, 0, 0),
                            BranchId = 1,
                            EMail = "diana.prince@example.com",
                            EmployeeId = 1,
                            Gender = 1,
                            Name = "Diana",
                            PhoneNumber = "+90 123 456 7894",
                            Price = 180m,
                            StartDateTime = new DateTime(2026, 1, 18, 9, 45, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            Surname = "Prince",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 5,
                            AgeGroupId = 1,
                            ApproximateDuration = new TimeSpan(0, 0, 35, 0, 0),
                            BranchId = 1,
                            EMail = "eve.adams@example.com",
                            EmployeeId = 2,
                            Gender = 1,
                            Name = "Eve",
                            PhoneNumber = "+90 123 456 7895",
                            Price = 160m,
                            StartDateTime = new DateTime(2026, 1, 18, 16, 15, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            Surname = "Adams",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 6,
                            AgeGroupId = 2,
                            ApproximateDuration = new TimeSpan(0, 0, 30, 0, 0),
                            BranchId = 1,
                            EMail = "frank.miller@example.com",
                            EmployeeId = 3,
                            Gender = 0,
                            Name = "Frank",
                            PhoneNumber = "+90 123 456 7896",
                            Price = 120m,
                            StartDateTime = new DateTime(2026, 1, 16, 12, 30, 0, 0, DateTimeKind.Local),
                            Status = 0,
                            Surname = "Miller",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 7,
                            AgeGroupId = 1,
                            ApproximateDuration = new TimeSpan(0, 1, 15, 0, 0),
                            BranchId = 1,
                            EMail = "grace.hall@example.com",
                            EmployeeId = 2,
                            Gender = 1,
                            Name = "Grace",
                            PhoneNumber = "+90 123 456 7897",
                            Price = 450m,
                            StartDateTime = new DateTime(2026, 1, 16, 15, 0, 0, 0, DateTimeKind.Local),
                            Status = 1,
                            Surname = "Hall",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 8,
                            AgeGroupId = 3,
                            ApproximateDuration = new TimeSpan(0, 1, 45, 0, 0),
                            BranchId = 1,
                            EMail = "henry.ford@example.com",
                            EmployeeId = 1,
                            Gender = 0,
                            Name = "Henry",
                            PhoneNumber = "+90 123 456 7898",
                            Price = 700m,
                            StartDateTime = new DateTime(2026, 1, 16, 14, 30, 0, 0, DateTimeKind.Local),
                            Status = 3,
                            Surname = "Ford",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 9,
                            AgeGroupId = 3,
                            ApproximateDuration = new TimeSpan(0, 0, 45, 0, 0),
                            BranchId = 1,
                            EMail = "isabelle.clark@example.com",
                            EmployeeId = 3,
                            Gender = 1,
                            Name = "Isabelle",
                            PhoneNumber = "+90 123 456 7899",
                            Price = 250m,
                            StartDateTime = new DateTime(2026, 1, 16, 10, 0, 0, 0, DateTimeKind.Local),
                            Status = 2,
                            Surname = "Clark",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            CustomerAppointmentId = 10,
                            AgeGroupId = 1,
                            ApproximateDuration = new TimeSpan(0, 1, 0, 0, 0),
                            BranchId = 1,
                            EMail = "jack.white@example.com",
                            EmployeeId = 2,
                            Gender = 0,
                            Name = "Jack",
                            PhoneNumber = "+90 123 456 7890",
                            Price = 300m,
                            StartDateTime = new DateTime(2026, 1, 17, 9, 15, 0, 0, DateTimeKind.Local),
                            Status = 0,
                            Surname = "White",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<int>("BranchId")
                        .HasColumnType("int");

                    b.Property<bool>("CanTakeClients")
                        .HasColumnType("bit");

                    b.Property<int>("DayOff")
                        .HasColumnType("int");

                    b.Property<string>("EmployeeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("EndOfWorkingHours")
                        .HasColumnType("time");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan>("StartOfWorkingHours")
                        .HasColumnType("time");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeId");

                    b.HasIndex("BranchId");

                    b.HasIndex("TenantId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            BranchId = 1,
                            CanTakeClients = true,
                            DayOff = 0,
                            EmployeeName = "Aydın",
                            EmployeeSurname = "Sevim",
                            EndOfWorkingHours = new TimeSpan(0, 19, 0, 0, 0),
                            IdentityUserId = "1",
                            StartOfWorkingHours = new TimeSpan(0, 10, 0, 0, 0),
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            EmployeeId = 2,
                            BranchId = 1,
                            CanTakeClients = true,
                            DayOff = 0,
                            EmployeeName = "Alpay",
                            EmployeeSurname = "Aydıngüler",
                            EndOfWorkingHours = new TimeSpan(0, 19, 0, 0, 0),
                            IdentityUserId = "2",
                            StartOfWorkingHours = new TimeSpan(0, 10, 0, 0, 0),
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            EmployeeId = 3,
                            BranchId = 1,
                            CanTakeClients = false,
                            DayOff = 0,
                            EmployeeName = "Deniz",
                            EmployeeSurname = "Dağ",
                            EndOfWorkingHours = new TimeSpan(0, 19, 0, 0, 0),
                            IdentityUserId = "3",
                            StartOfWorkingHours = new TimeSpan(0, 10, 0, 0, 0),
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Entities.Models.EmployeeLeave", b =>
                {
                    b.Property<int>("EmployeeLeaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeLeaveId"));

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("LeaveEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LeaveStartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Reason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EmployeeLeaveId");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TenantId");

                    b.ToTable("EmployeeLeaves");

                    b.HasData(
                        new
                        {
                            EmployeeLeaveId = 1,
                            EmployeeId = 1,
                            LeaveEndDateTime = new DateTime(2026, 1, 16, 18, 0, 0, 0, DateTimeKind.Local),
                            LeaveStartDateTime = new DateTime(2026, 1, 16, 8, 0, 0, 0, DateTimeKind.Local),
                            Reason = "Sick",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            EmployeeLeaveId = 2,
                            EmployeeId = 2,
                            LeaveEndDateTime = new DateTime(2026, 1, 17, 18, 0, 0, 0, DateTimeKind.Local),
                            LeaveStartDateTime = new DateTime(2026, 1, 17, 8, 0, 0, 0, DateTimeKind.Local),
                            Reason = "Vacation",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            EmployeeLeaveId = 3,
                            EmployeeId = 3,
                            LeaveEndDateTime = new DateTime(2026, 1, 18, 18, 0, 0, 0, DateTimeKind.Local),
                            LeaveStartDateTime = new DateTime(2026, 1, 18, 8, 0, 0, 0, DateTimeKind.Local),
                            Reason = "Personal",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Entities.Models.OfferedService", b =>
                {
                    b.Property<int>("OfferedServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferedServiceId"));

                    b.Property<TimeSpan>("ApproximateDuration")
                        .HasColumnType("time");

                    b.PrimitiveCollection<string>("Genders")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OfferedServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OfferedServiceId");

                    b.HasIndex("TenantId");

                    b.ToTable("OfferedServices", t =>
                        {
                            t.HasCheckConstraint("CK_OfferedService_ApproximateDuration", "ApproximateDuration >= '00:01' AND ApproximateDuration <= '23:59'");
                        });

                    b.HasData(
                        new
                        {
                            OfferedServiceId = 1,
                            ApproximateDuration = new TimeSpan(0, 0, 20, 0, 0),
                            Genders = "[0]",
                            OfferedServiceName = "HairCut",
                            Price = 100m,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 2,
                            ApproximateDuration = new TimeSpan(0, 0, 40, 0, 0),
                            Genders = "[0]",
                            OfferedServiceName = "RazorShave",
                            Price = 200m,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 3,
                            ApproximateDuration = new TimeSpan(0, 1, 0, 0, 0),
                            Genders = "[0]",
                            OfferedServiceName = "HairColoring",
                            Price = 300m,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 4,
                            ApproximateDuration = new TimeSpan(0, 1, 20, 0, 0),
                            Genders = "[0,1]",
                            OfferedServiceName = "BrowShaping",
                            Price = 400m,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 5,
                            ApproximateDuration = new TimeSpan(0, 1, 40, 0, 0),
                            Genders = "[0,1]",
                            OfferedServiceName = "BeardGrooming",
                            Price = 500m,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 6,
                            ApproximateDuration = new TimeSpan(0, 2, 0, 0, 0),
                            Genders = "[0,1]",
                            OfferedServiceName = "ChildShave",
                            Price = 600m,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 7,
                            ApproximateDuration = new TimeSpan(0, 2, 20, 0, 0),
                            Genders = "[0,1]",
                            OfferedServiceName = "PermHair",
                            Price = 700m,
                            Status = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 8,
                            ApproximateDuration = new TimeSpan(0, 2, 30, 0, 0),
                            Genders = "[0,1]",
                            OfferedServiceName = "Manicure",
                            Price = 800m,
                            Status = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 9,
                            ApproximateDuration = new TimeSpan(0, 2, 40, 0, 0),
                            Genders = "[0,1]",
                            OfferedServiceName = "Pedicure",
                            Price = 900m,
                            Status = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 10,
                            ApproximateDuration = new TimeSpan(0, 3, 0, 0, 0),
                            Genders = "[0]",
                            OfferedServiceName = "GroomsCut",
                            Price = 1000m,
                            Status = true,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceId = 11,
                            ApproximateDuration = new TimeSpan(0, 3, 20, 0, 0),
                            Genders = "[1]",
                            OfferedServiceName = "Makeup(Bride)",
                            Price = 1100m,
                            Status = false,
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Entities.Models.OfferedServiceLocalization", b =>
                {
                    b.Property<int>("OfferedServiceLocalizationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OfferedServiceLocalizationId"));

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OfferedServiceId")
                        .HasColumnType("int");

                    b.Property<string>("OfferedServiceLocalizationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("OfferedServiceLocalizationId");

                    b.HasIndex("OfferedServiceId");

                    b.HasIndex("TenantId");

                    b.ToTable("OfferedServiceLocalizations");

                    b.HasData(
                        new
                        {
                            OfferedServiceLocalizationId = 1,
                            Language = "en-GB",
                            OfferedServiceId = 1,
                            OfferedServiceLocalizationName = "Hair Cut",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 2,
                            Language = "tr-TR",
                            OfferedServiceId = 1,
                            OfferedServiceLocalizationName = "Saç Kesimi",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 3,
                            Language = "en-GB",
                            OfferedServiceId = 2,
                            OfferedServiceLocalizationName = "Razor Shave",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 4,
                            Language = "tr-TR",
                            OfferedServiceId = 2,
                            OfferedServiceLocalizationName = "Jilet Traşı",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 5,
                            Language = "en-GB",
                            OfferedServiceId = 3,
                            OfferedServiceLocalizationName = "Hair Coloring",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 6,
                            Language = "tr-TR",
                            OfferedServiceId = 3,
                            OfferedServiceLocalizationName = "Saç Boyama",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 7,
                            Language = "en-GB",
                            OfferedServiceId = 4,
                            OfferedServiceLocalizationName = "Brow Shaping",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 8,
                            Language = "tr-TR",
                            OfferedServiceId = 4,
                            OfferedServiceLocalizationName = "Kaş Şekillendirme",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 9,
                            Language = "en-GB",
                            OfferedServiceId = 5,
                            OfferedServiceLocalizationName = "Beard Grooming",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 10,
                            Language = "tr-TR",
                            OfferedServiceId = 5,
                            OfferedServiceLocalizationName = "Sakal Bakımı",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 11,
                            Language = "en-GB",
                            OfferedServiceId = 6,
                            OfferedServiceLocalizationName = "Child Shave",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 12,
                            Language = "tr-TR",
                            OfferedServiceId = 6,
                            OfferedServiceLocalizationName = "Çocuk Tıraşı",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 13,
                            Language = "en-GB",
                            OfferedServiceId = 7,
                            OfferedServiceLocalizationName = "Perm Hair",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 14,
                            Language = "tr-TR",
                            OfferedServiceId = 7,
                            OfferedServiceLocalizationName = "Perma Saç",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 15,
                            Language = "en-GB",
                            OfferedServiceId = 8,
                            OfferedServiceLocalizationName = "Manicure",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 16,
                            Language = "tr-TR",
                            OfferedServiceId = 8,
                            OfferedServiceLocalizationName = "Manikür",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 17,
                            Language = "en-GB",
                            OfferedServiceId = 9,
                            OfferedServiceLocalizationName = "Pedicure",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 18,
                            Language = "tr-TR",
                            OfferedServiceId = 9,
                            OfferedServiceLocalizationName = "Pedikür",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 19,
                            Language = "en-GB",
                            OfferedServiceId = 10,
                            OfferedServiceLocalizationName = "Groom's Cut",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 20,
                            Language = "tr-TR",
                            OfferedServiceId = 10,
                            OfferedServiceLocalizationName = "Damat Kesimi",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 21,
                            Language = "en-GB",
                            OfferedServiceId = 11,
                            OfferedServiceLocalizationName = "Makeup (Bride)",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        },
                        new
                        {
                            OfferedServiceLocalizationId = 22,
                            Language = "tr-TR",
                            OfferedServiceId = 11,
                            OfferedServiceLocalizationName = "Makyaj (Gelin)",
                            TenantId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("Entities.Models.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Hostname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2023, 11, 17, 11, 37, 29, 0, DateTimeKind.Utc),
                            Hostname = "localhost",
                            Name = "Default Tenant"
                        },
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            CreatedAt = new DateTime(2024, 11, 17, 11, 37, 29, 0, DateTimeKind.Utc),
                            Hostname = "company1.com",
                            Name = "Company1"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            CreatedAt = new DateTime(2025, 11, 17, 11, 37, 29, 0, DateTimeKind.Utc),
                            Hostname = "company2.com",
                            Name = "Company2"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Owner",
                            NormalizedName = "OWNER"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Editor",
                            NormalizedName = "EDITOR"
                        },
                        new
                        {
                            Id = "4",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("OfferedServiceAgeGroups", b =>
                {
                    b.Property<int>("AgeGroupsId")
                        .HasColumnType("int");

                    b.Property<int>("OfferedServiceId")
                        .HasColumnType("int");

                    b.HasKey("AgeGroupsId", "OfferedServiceId");

                    b.HasIndex("OfferedServiceId");

                    b.ToTable("OfferedServiceAgeGroups");

                    b.HasData(
                        new
                        {
                            AgeGroupsId = 1,
                            OfferedServiceId = 1
                        },
                        new
                        {
                            AgeGroupsId = 2,
                            OfferedServiceId = 2
                        },
                        new
                        {
                            AgeGroupsId = 1,
                            OfferedServiceId = 3
                        },
                        new
                        {
                            AgeGroupsId = 2,
                            OfferedServiceId = 3
                        },
                        new
                        {
                            AgeGroupsId = 1,
                            OfferedServiceId = 4
                        },
                        new
                        {
                            AgeGroupsId = 1,
                            OfferedServiceId = 5
                        },
                        new
                        {
                            AgeGroupsId = 2,
                            OfferedServiceId = 5
                        },
                        new
                        {
                            AgeGroupsId = 1,
                            OfferedServiceId = 6
                        },
                        new
                        {
                            AgeGroupsId = 2,
                            OfferedServiceId = 7
                        },
                        new
                        {
                            AgeGroupsId = 2,
                            OfferedServiceId = 8
                        },
                        new
                        {
                            AgeGroupsId = 2,
                            OfferedServiceId = 9
                        },
                        new
                        {
                            AgeGroupsId = 2,
                            OfferedServiceId = 10
                        },
                        new
                        {
                            AgeGroupsId = 2,
                            OfferedServiceId = 11
                        });
                });

            modelBuilder.Entity("CustomerAppointmentOfferedServices", b =>
                {
                    b.HasOne("Entities.Models.CustomerAppointment", null)
                        .WithMany()
                        .HasForeignKey("CustomerAppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.OfferedService", null)
                        .WithMany()
                        .HasForeignKey("OfferedServicesId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EmployeeOfferedServices", b =>
                {
                    b.HasOne("Entities.Models.Employee", null)
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.OfferedService", null)
                        .WithMany()
                        .HasForeignKey("OfferedServicesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.AgeGroup", b =>
                {
                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.ApplicationSetting", b =>
                {
                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.ApplicationUser", b =>
                {
                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.BookingFlowConfig", b =>
                {
                    b.HasOne("Entities.Models.Branch", "Branch")
                        .WithMany()
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.Branch", b =>
                {
                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.CustomerAppointment", b =>
                {
                    b.HasOne("Entities.Models.AgeGroup", "AgeGroup")
                        .WithMany("CustomerAppointments")
                        .HasForeignKey("AgeGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.Branch", "Branch")
                        .WithMany("CustomerAppointment")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Employee", "Employee")
                        .WithMany("CustomerAppointment")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AgeGroup");

                    b.Navigation("Branch");

                    b.Navigation("Employee");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.HasOne("Entities.Models.Branch", "Branch")
                        .WithMany("Employee")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.EmployeeLeave", b =>
                {
                    b.HasOne("Entities.Models.Employee", "Employee")
                        .WithMany("EmployeesLeaves")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.OfferedService", b =>
                {
                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Entities.Models.OfferedServiceLocalization", b =>
                {
                    b.HasOne("Entities.Models.OfferedService", "OfferedService")
                        .WithMany("OfferedServiceLocalizations")
                        .HasForeignKey("OfferedServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OfferedService");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Entities.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OfferedServiceAgeGroups", b =>
                {
                    b.HasOne("Entities.Models.AgeGroup", null)
                        .WithMany()
                        .HasForeignKey("AgeGroupsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Entities.Models.OfferedService", null)
                        .WithMany()
                        .HasForeignKey("OfferedServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Entities.Models.AgeGroup", b =>
                {
                    b.Navigation("CustomerAppointments");
                });

            modelBuilder.Entity("Entities.Models.Branch", b =>
                {
                    b.Navigation("CustomerAppointment");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Entities.Models.Employee", b =>
                {
                    b.Navigation("CustomerAppointment");

                    b.Navigation("EmployeesLeaves");
                });

            modelBuilder.Entity("Entities.Models.OfferedService", b =>
                {
                    b.Navigation("OfferedServiceLocalizations");
                });
#pragma warning restore 612, 618
        }
    }
}
