//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LudusAppoint.Resources.Areas.Admin.Controllers {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CustomerAppointmentController {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CustomerAppointmentController() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LudusAppoint.Resources.Areas.Admin.Controllers.CustomerAppointmentController", typeof(CustomerAppointmentController).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No employees available..
        /// </summary>
        public static string NoEmployeesAvailable_ {
            get {
                return ResourceManager.GetString("NoEmployeesAvailable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No offered services available..
        /// </summary>
        public static string NoOfferedServicesAvailable_ {
            get {
                return ResourceManager.GetString("NoOfferedServicesAvailable.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try with diffrent age group or gender..
        /// </summary>
        public static string PleaseTryWithDiffrentAgeGroupOrGender_ {
            get {
                return ResourceManager.GetString("PleaseTryWithDiffrentAgeGroupOrGender.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try with diffrent branch or offered services..
        /// </summary>
        public static string PleaseTryWithDiffrentBranchOrOfferedServices_ {
            get {
                return ResourceManager.GetString("PleaseTryWithDiffrentBranchOrOfferedServices.", resourceCulture);
            }
        }
    }
}
