//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Services.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AgeGroupManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AgeGroupManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Services.Resources.AgeGroupManager", typeof(AgeGroupManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age cannot be negative.
        /// </summary>
        internal static string AgeCannotBeNegative {
            get {
                return ResourceManager.GetString("AgeCannotBeNegative", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age cannot be negative..
        /// </summary>
        internal static string AgeCannotBeNegative_ {
            get {
                return ResourceManager.GetString("AgeCannotBeNegative.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age group cannot be deleted because ıt ıs used ın another entity.
        /// </summary>
        internal static string AgeGroupCannotBeDeletedBecauseItIsUsedInAnotherEntity {
            get {
                return ResourceManager.GetString("AgeGroupCannotBeDeletedBecauseItIsUsedInAnotherEntity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Age group cannot be deleted because ıt ıs used ın another entity..
        /// </summary>
        internal static string AgeGroupCannotBeDeletedBecauseItIsUsedInAnotherEntity_ {
            get {
                return ResourceManager.GetString("AgeGroupCannotBeDeletedBecauseItIsUsedInAnotherEntity.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An age group with the same min age and max age already exists.
        /// </summary>
        internal static string AnAgeGroupWithTheSameMinAgeAndMaxAgeAlreadyExists {
            get {
                return ResourceManager.GetString("AnAgeGroupWithTheSameMinAgeAndMaxAgeAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto cannot be null.
        /// </summary>
        internal static string DtoCannotBeNull {
            get {
                return ResourceManager.GetString("DtoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dto cannot be null..
        /// </summary>
        internal static string DtoCannotBeNull_ {
            get {
                return ResourceManager.GetString("DtoCannotBeNull.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age cannot be greater than maximum age.
        /// </summary>
        internal static string MinimumAgeCannotBeGreaterThanMaximumAge {
            get {
                return ResourceManager.GetString("MinimumAgeCannotBeGreaterThanMaximumAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum age cannot be greater than maximum age..
        /// </summary>
        internal static string MinimumAgeCannotBeGreaterThanMaximumAge_ {
            get {
                return ResourceManager.GetString("MinimumAgeCannotBeGreaterThanMaximumAge.", resourceCulture);
            }
        }
    }
}
