//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BranchDto {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BranchDto() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Entities.Resources.BranchDto", typeof(BranchDto).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot exceed200 characters.
        /// </summary>
        public static string AddressCannotExceed200Characters {
            get {
                return ResourceManager.GetString("AddressCannotExceed200Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch name cannot exceed100 characters.
        /// </summary>
        public static string BranchNameCannotExceed100Characters {
            get {
                return ResourceManager.GetString("BranchNameCannotExceed100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City cannot exceed50 characters.
        /// </summary>
        public static string CityCannotExceed50Characters {
            get {
                return ResourceManager.GetString("CityCannotExceed50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country cannot exceed50 characters.
        /// </summary>
        public static string CountryCannotExceed50Characters {
            get {
                return ResourceManager.GetString("CountryCannotExceed50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to District cannot exceed50 characters.
        /// </summary>
        public static string DistrictCannotExceed50Characters {
            get {
                return ResourceManager.GetString("DistrictCannotExceed50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot exceed100 characters.
        /// </summary>
        public static string EmailCannotExceed100Characters {
            get {
                return ResourceManager.GetString("EmailCannotExceed100Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neighbourhood cannot exceed50 characters.
        /// </summary>
        public static string NeighbourhoodCannotExceed50Characters {
            get {
                return ResourceManager.GetString("NeighbourhoodCannotExceed50Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number cannot exceed15 characters.
        /// </summary>
        public static string PhoneNumberCannotExceed15Characters {
            get {
                return ResourceManager.GetString("PhoneNumberCannotExceed15Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation ın advance day limit must be between1 and365.
        /// </summary>
        public static string ReservationInAdvanceDayLimitMustBeBetween1And365 {
            get {
                return ResourceManager.GetString("ReservationInAdvanceDayLimitMustBeBetween1And365", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street cannot exceed100 characters.
        /// </summary>
        public static string StreetCannotExceed100Characters {
            get {
                return ResourceManager.GetString("StreetCannotExceed100Characters", resourceCulture);
            }
        }
    }
}
